[project]
name = "llms-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "gradio>=6.27.0",
    "ipykernel>=7.3.0",
    "langchain>=1.4.0",
    "langchain-openai>=1.6.2",
    "litellm>=1.83.0",
    "ollama>=0.6.2",
    "openai>=3.10.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
llms-course = "llms_course:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
[tool.uv]
package = false
